Исправила авторизацию
friends-locator/backend pull request #10
Opened 2023-06-20 18:48 UTC by ifyoumasha

Поменяла валидацию в сериализаторе CustomUserCreateSerializer и поля max_lenght в модели CustomUser согласно фич-листу 

Настроила эндпоинты:
http://127.0.0.1:8000/users/v1/users/ - создание пользователя
http://127.0.0.1:8000/users/v1/jwt/create/ - получение токена
http://127.0.0.1:8000/users/v1/users/me/ - информация о юзере
http://127.0.0.1:8000/users/v1/users/set_password/ - смена пароля

2023-06-20 23:23 UTC, IhateChoosingNickNames requested changes
В целом: норм. Кое-что подправить и можно заливать.
Из критического: подправить регулярки.
Из среднего: подправить некоторые валидаторы.
Все остальное - косметика.
P.S. Удали свой старый ПР.

2023-06-20 23:23 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +        if not match(r'^[А-Я][а-я][A-Z][a-z]+,?\s+', value):
Эта регулярка обозначает: первая буква будет русской заглавной, вторая буква русская строчная, третья буква латинская заглавная, затем 1 и более строчных латинских букв, запятая (которой может не быть), а затем 1 и более пробела. То есть, условное имя "Михаил" эта регулярка не пропустит.
Если нужно сделать выборку, то все нужно в квадратные скобки. К примеру: [a-яА-Яa-zA-Z ]+ - такой паттерн уже нормально отработает.

2023-06-20 23:23 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +    def validate_email(self, value):
Этот валидатор вообще не нужен: валидация самой строки мейла произойдет и так. Как и проверка уникальности - у нас unique=True стоит.
Я вообще не вижу смысла, зачем тебе это дублирование.

2023-06-20 23:23 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +        if len(value) < 8:
Первый if также не нужен - 8 символов это дефолтное джанговское ограничение.

2023-06-20 23:23 UTC, IhateChoosingNickNames commented on backend/users/views.py
> +class CustomUserViewSet(UserViewSet):
Докстринга.

2023-06-20 23:23 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +    """Кастомный сериализатор для работы с пользователем."""
Тут, кстати, определись: после докстринги в классе ставишь пустую строку или нет. Лично я за то, чтобы ставить. Но ни тот, ни другой вариант не противоречит ПЕП. Просто чисто консистентности ради стоит придерживаться чего-то одного.

2023-06-21 14:01 UTC, IhateChoosingNickNames approved these changes
В целом - найс.
Только потом надо будет не забыть пробел в регулярку добавить и длину строки нормально выставить.

2023-06-21 20:19 UTC, saminter22 approved these changes

2023-06-21 20:20 UTC, merged