Добавление вьюх по передаче координат и получению друзей по координатам
friends-locator/backend pull request #127
Opened 2023-07-14 17:19 UTC by LevityLoveLight

1. Переписал вью функцию по обновлению координат в модели User.
2. Переписал вью функцию по получению друзей по координатам.

2023-07-14 18:52 UTC, IhateChoosingNickNames requested changes
Я бы, все же, заюзал отдельный сериализатор для обновления координат.
Ибо там тебе вообще только 2 поля нужны, а все остальное - балласт.
Пофиксить этот момент и запрос - и все норм.

2023-07-14 18:52 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +    def validate(self, data):
По этой логике нельзя будет даже зарегистрировать пользователя без координат.
А у нас, вроде бы, должна быть такая логика.
Лучше создай отдельный сериализатор, либо как-то учти этот момент.
Тебе нужно: 1. Создавать пользователя без координат. 2. Создавать пользователя с координатами. 3. Обновлять координаты у конкретного пользователя.

2023-07-14 18:52 UTC, IhateChoosingNickNames commented on backend/users/views.py
> +        nearby_friends = User.objects.filter(
У тебя выше уже есть список всех друзей. И его нужно отфильтровать. А ты опять сначала достаешь всех друзей, а потом уже фильтруешь.
Просто .all() замени на этот .filter().

2023-07-15 08:50 UTC, LevityLoveLight commented
1. Добавлен отдельный сериализатор с валидацией по координатам  
2. Оптимизирован запроса к бд по поиску друзей по координатам

2023-07-15 14:24 UTC, merged