Добавлена модель CustomUser
friends-locator/backend pull request #3
Opened 2023-06-14 16:42 UTC by sheremet-o

Добавлены модели: CustomUser, Tag, Status
В админке зарегистрирован CustomUser

2023-06-14 17:27 UTC, IhateChoosingNickNames requested changes
Часть нужно исправить, остальные - на твое усмотрение.

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
> +    gender = models.CharField(choices=GENDERS, default="male")
И, все же, "male" очень похоже на хардкодинг.
Я бы вынес оба гендера в константы на уровне текущего класса и сюда передавал бы уже константу.
А в случае, если завтра male начнет называться male111, то ты изменения выносится будут на уровне констант выше, а не в полях модели.

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
А зачем тут пустая строка?

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
> +from colorfields.fields import ColorField
Это стороння либа? Если да - то ее стоит в requirements.txt занести.

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/backend/settings.py
> +AUTH_USER_MODEL = "user.CustomUser"
user**S**.CustomUser?

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
> +        return f"{self.first_name} {self.last_name}"
И то, и другое поле имеют допустимые пределы в 150 символов.
То есть потенциально вот это может быть строка из 300 символов.
Если с этим все ок - то все норм.

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
> +    class Meta:
Для тегов и статусов я бы добавил ordering = "name".
Как по мне - это будет иметь больший смысл, чем дефолтная сортировка по id.

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
> +    name = models.CharField(max_length=50)
Думаю, есть смысл и имя сделать уникальным. В Status тоже.

2023-06-14 17:27 UTC, IhateChoosingNickNames commented on backend/users/models.py
> +    slug = models.SlugField(max_length=50, unique=True)
Я бы сделал тут автоматическое создание слага. На данный момент это все перекладывается на руки админа.
Точно уже не скажу насчет дефолтных нормальных способов, но можно:
1. Переопределить save() и в нем перед созданием использовать либу slugify
2. auto_created=True - но тут гугли, я не совсем уверен, что это работать будет.
3. Самое адекватное - prepopulated_fields в админке. Если полагается, что теги/статусы будет создавать админ, то и логично было бы это все в админку выносить.
https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.prepopulated_fields:~:text=ModelAdmin.get_paginator().-,ModelAdmin.prepopulated_fields,-%C2%B6

2023-06-15 21:35 UTC, saminter22 approved these changes

2023-06-15 21:36 UTC, merged