Feature/auth
friends-locator/backend pull request #6
Opened 2023-06-17 07:32 UTC by ifyoumasha

Добавлена авторизация. Сделала кастомный сериализатор, добавила валидацию и вьюсет. Жду ваших комментариев и предложений.

2023-06-17 08:16 UTC, saminter22 commented on backend/backend/urls.py
> +    path('api/', include('users.urls'))
давайте версионировать api 
/v1/ например

2023-06-17 08:21 UTC, saminter22 commented on backend/users/serializers.py
> +User = get_user_model()
здесь и далее разве не CustomUser?

2023-06-17 08:21 UTC, saminter22 reviewed
код работает?

2023-06-17 11:13 UTC, IhateChoosingNickNames commented on backend/backend/urls.py
> +    path('api/', include('users.urls'))
Это корневые урлы, тут достаточно api/. Версионность нужно отражать непосредственно в приложении.

2023-06-17 11:15 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +User = get_user_model()
get_user_model - вернет текущую дефолтную модель юзеров.
После регистрации в сеттингах, эта функция будет возвращать корректную модель.
Лучше оставить эту функцию, т.к. в случае если изменится имя модели, то не придется лезть сюда и править.

2023-06-17 11:53 UTC, IhateChoosingNickNames requested changes
В общем и целом: проверь работоспособность всей этой конструкции.
Я сейчас залью свой предыдущий ПР - подтяни его и проверь, чтобы твой код работал.

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +    def validate_username(self, value):
А вот эти 2 метода точно нужны? У нас такие валидаторы в моделях стоят - регулярка на юзернейме и уникальность на мейле. UserCreateSerializer наследуется от ModelSerializer и модель там указывается User (текущая дефолтная).
То есть, все эти ограничения должны по дефолту подтянуться из модели.
Этот момент стоит проверить.

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/users/urls.py
> +    path('auth/', include('djoser.urls')),
А вот здесь уже лучше добавить версионность: v1/

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/backend/settings.py
В настройки еще нужно вынести настроку самого Djoser (как минимум зарегистрировать сериализатор):
https://djoser.readthedocs.io/en/latest/settings.html

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/backend/settings.py
> +       'rest_framework_simplejwt.authentication.JWTAuthentication',
Сам simplejwt дополнительно ставить не на надо?
Потом надо не забыть это проверить.

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +    def validate_password(self, value):
Хм, странный валидатор, как по мне. Для системы пароль в 20+ символов ничего плохого не сделает, а если пользователю удобно такой пароль юзать - то, как по мне, пусть юзает.

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
>          if not match(r'[\w.@+\-]+', value):
Эта регулярка даст возможность пользователю выбрать себе имя (именно имя): "а121@@@-". Не думаю, что регулярку для мейлов удачно юзать для валидации имени.
Для last_name cитуация та же.

2023-06-17 11:53 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +        if len(value) > 100:
Тоже странное условие - у нас в модели max_length стоит в 150 символов.
Этот сериализатор должен оттуда подтягивать валидацию.

2023-06-19 18:44 UTC, ifyoumasha commented on backend/users/serializers.py
> +    def validate_username(self, value):
На мой взгляд, валидировать лучше и со стороны запроса и со стороны БД, но это можно обсудить.

2023-06-19 18:46 UTC, ifyoumasha commented on backend/users/urls.py
> +    path('auth/', include('djoser.urls')),
Тогда может быть версионность стоит прописать в головном urls.py?

2023-06-19 19:24 UTC, IhateChoosingNickNames commented on backend/users/serializers.py
> +    def validate_username(self, value):
В целом, да, больше валидации - не меньше валидации.
Но когда у тебя валидация одна и та же - то тут уже возникают вопросы на тему того, почему ты не доверяешь ModelSerializer.
Добавить какую-то дополнительную валидацию - да, можно. Но прям 1 в 1 - это странно, как по мне.

2023-06-19 19:28 UTC, IhateChoosingNickNames commented on backend/users/urls.py
> +    path('auth/', include('djoser.urls')),
Если отражать в коревых урлах, то если у тебя появится 2 версия, то тебе придется создавать еще одно приложение и снова его регистрировать, но с другим урлом api/v2/.
В пределах одного приложения у тебя уже не получится это сделать.
Ну, в целом, смотри сама. Но создавать новое прилоежение, где половина функционала будет дублироваться, как по мне, будет оправдано только в случае, если появятся прям грандиозные изменения, которые нужно будет выносить.

2023-06-21 13:28 UTC, closed without merging